- hosts: all
  become: true
  tasks:
    - name: Idle timeout for the instance
      command: sed -i 's/^ClientAliveInterval 0/ClientAliveInterval 300/' /etc/ssh/sshd_config
      register: vm_status
    - name: Disable Root login
      command: sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
      when: vm_status.changed